# Generated by Django 4.1.5 on 2023-01-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_status_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
