# Generated by Django 4.1.5 on 2023-01-13 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("sub_total", models.FloatField(default=0)),
                ("grand_total", models.FloatField(default=0)),
                ("tax_amount", models.FloatField(default=0)),
                ("tax_percentage", models.FloatField(default=0)),
                ("amount_payed", models.FloatField(default=0)),
                ("amount_change", models.FloatField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        db_column="customer",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "Sales",
            },
        ),
    ]
