# Generated by Django 4.1.5 on 2023-01-13 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_category_options_alter_product_status"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("subtotal_detail", models.FloatField()),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="products.product",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        db_column="sale",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "db_table": "SaleDetails",
            },
        ),
    ]
