# Generated by Django 4.1.5 on 2023-01-14 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_saledetail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="saledetail",
            old_name="venta",
            new_name="sale",
        ),
        migrations.RenameField(
            model_name="saledetail",
            old_name="subtotal_detail",
            new_name="total_detail",
        ),
    ]
