# Generated by Django 4.1.5 on 2023-01-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=256)),
                ("last_name", models.CharField(blank=True, max_length=256, null=True)),
                ("address", models.TextField(blank=True, max_length=256, null=True)),
                ("email", models.EmailField(blank=True, max_length=256, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "Customers",
            },
        ),
    ]
